import './globals.css'
import Header from '@/app/Header';
import {cookies} from 'next/headers';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    const cookieStore = cookies();
    const username = cookieStore.get('username');

    return (
        <html lang="en">
        <body>
        <Header username={username?.value}/>
        {children}
        </body>
        </html>
    )
}
